services:
  spark-env:
    build:
      context: .
    image: alwolmer/radar-prf-101:latest
    container_name: radar_prf_101_spark
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - uv-cache:/tmp/uv-cache
    environment:
      SPARK_MODE: local
      DATALAKE_BACKEND: local
      DATALAKE_LOCAL_ROOT: /app/data
      PYSPARK_PYTHON: python3
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  uv-cache:
