"""Constantes de causas de acidente categorizadas."""

CAUSAS_ACIDENTE_POR_CATEGORIA = {
    "conduta_ou_condicao_do_condutor": [
        "Condutor Dormindo",
        "Falta de Atenção à Condução",
        "Não guardar distância de segurança",
        "Velocidade Incompatível",
        "Ultrapassagem Indevida",
        "Ingestão de Álcool",
        "Desobediência às normas de trânsito pelo condutor",
        "Mal Súbito",
        "Ingestão de Substâncias Psicoativas",
        "Ingestão de álcool pelo condutor",
        "Ausência de reação do condutor",
        "Reação tardia ou ineficiente do condutor",
        "Manobra de mudança de faixa",
        "Transitar na contramão",
        "Condutor deixou de manter distância do veículo da frente",
        "Deixar de acionar o farol da motocicleta (ou similar)",
        "Transitar no Acostamento",
        "Suicídio (presumido)",
        "Transtornos Mentais (exceto suicidio)",
        "Mal súbito do condutor",
        "Acessar a via sem observar a presença dos outros veículos",
        "Trafegar com motocicleta (ou similar) entre as faixas",
        "Transitar no acostamento",
        "Estacionar ou parar em local proibido",
        "Desrespeitar a preferência no cruzamento",
        "Condutor desrespeitou a iluminação vermelha do semáforo",
        "Acesso irregular",
        "Ingestão de substâncias psicoativas pelo condutor",
        "Condutor usando celular",
        "Retorno proibido",
        "Transitar na calçada",
        "Participar de racha",
        "Conversão proibida",
        "Frear",
    ],
    "condicao_da_via": [
        "Defeito na Via",
        "Pista Escorregadia",
        "Objeto estático sobre o leito carroçável",
        "Sinalização da via insuficiente ou inadequada",
        "Restrição de Visibilidade",
        "Curva acentuada",
        "Obras na pista",
        "Demais falhas na via",
        "Área urbana sem a presença de local apropriado para a travessia de pedestres",
        "Desvio temporário",
        "Sinalização mal posicionada",
        "Declive acentuado",
        "Falta de elemento de contenção que evite a saída do leito carroçável",
        "Restrição de visibilidade em curvas verticais",
        "Acumulo de água sobre o pavimento",
        "Acostamento em desnível",
        "Ausência de sinalização",
        "Obstrução na via",
        "Iluminação deficiente",
        "Acumulo de areia ou detritos sobre o pavimento",
        "Falta de acostamento",
        "Semáforo com defeito",
        "Deficiência do Sistema de Iluminação/Sinalização",
        "Acumulo de óleo sobre o pavimento",
        "Pista em desnível",
        "Pista esburacada",
        "Faixas de trânsito com largura insuficiente",
        "Afundamento ou ondulação no pavimento",
        "Sistema de drenagem ineficiente",
        "Sinalização encoberta",
        "Restrição de visibilidade em curvas horizontais",
        "Redutor de velocidade em desacordo",
    ],
    "condicao_do_veiculo": [
        "Defeito Mecânico no Veículo",
        "Avarias e/ou desgaste excessivo no pneu",
        "Demais falhas mecânicas ou elétricas",
        "Carga excessiva e/ou mal acondicionada",
        "Modificação proibida",
        "Problema na suspensão",
        "Deficiência ou não Acionamento do Sistema de Iluminação/Sinalização do Veículo",
        "Faróis desregulados",
        "Problema com o freio",
    ],
    "condicao_ou_conduta_do_pedestre_ou_agentes_fora_da_pista": [
        "Desobediência às normas de trânsito pelo pedestre",
        "Falta de Atenção do Pedestre",
        "Ingestão de álcool e/ou substâncias psicoativas pelo pedestre",
        "Pedestre cruzava a pista fora da faixa",
        "Pedestre andava na pista",
        "Entrada inopinada do pedestre",
        "Pedestre - Ingestão de álcool/ substâncias psicoativas",
        "Agressão Externa",
        "Obstrução Via tentativa Assalto",
        "Ingestão de álcool ou de substâncias psicoativas pelo pedestre",
    ],
    "condicao_ou_fenomeno_da_natureza": [
        "Fumaça",
        "Neblina",
        "Demais Fenômenos da natureza",
        "Fenômenos da Natureza",
        "Animais na Pista",
        "Chuva",
    ],
}